### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by august0815** [ricardojoserf/instagram-followers-bot#13]
what is the experience with instagram,  with the simple follower query. will the account  be blocked if I  use the api many times ,
only to se my following or followed accounts ?

**Comment by ricardojoserf** [comment]
Hi @august0815 , if you use this script to check you account statistics like followers and unfollowers you will have no problem. If you use the script for following a lot of people you will probably have problems, I do not use this but I know Instagram has restrictions, so be careful. If you have any other problem please let me know ;)
