### ISSUE TITLE
Not able to Login

### ISSUE THREAD

**Issue by Terril** [ricardojoserf/instagram-followers-bot#18]
## Specifications

 - Operative system: Mac OS

 - Version (e.g. Python version): 2.7

## Steps to Reproduce the Problem
 Ran the main.py script

I logged out of my account on Instagram and used the same credentials {Facebook Login}.

**Login not successful**
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 113, in main
    for i in api.getTotalSelfFollowers():
  File "/Users/terrilthomas/Documents/Python Projects/instagram-followers-bot/LevPasha/InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: InstagramAPI instance has no attribute 'username_id'

**Comment by ricardojoserf** [comment]
Hi @Terril , I understand it is working for you now, let me know if it does not work again in the future and i will reopen the issue ;)

**Comment by Terril** [comment]
Hi @ricardojoserf , This is specific to **Facebook** Login, and If the user has **2-step Auth**. In that case, there should be something wherein the user inputs the OTP or something similar that he has received.
