### ISSUE TITLE
Multiple query request

### ISSUE THREAD

**Issue by Terril** [ricardojoserf/instagram-followers-bot#19]
## Describe the solution you'd like

The script works well Thank you for sharing it.
But is it possible to use multiple queries together?

Like using TAG and LOCATION_ID together
## Any other context or screenshots about the feature request here
** python main.py -u username -p password -o follow-location|follow-tag -t 216978098 -t funny**

**Comment by ricardojoserf** [comment]
Hi Terril,

I will create a separated branch for that and let you know when it is programmed, ok?

Ricardo

**Comment by ricardojoserf** [comment]
Hi Terril,

I think this could work for you:

https://gist.github.com/ricardojoserf/a058de50c5feec0a0331e3c61c1c9667

The syntax would be:

python main.py funny -u username -p password -o follow-location -t 216978098

So add the tag in the first argument ("funny") and use the script just like if you are following people from a specific location. However, you will get much less people with this method. Let me know if it does not work for you.

Ricardo

**Comment by Terril** [comment]
- Thanks @ricardojoserf for your prompt reply. Surely will try the above and update you

**Comment by Terril** [comment]
@ricardojoserf Just to update you. Tried the script shared but it didn't work
