### ISSUE TITLE
[appreciation]

### ISSUE THREAD

**Issue by quadroli** [ricardojoserf/instagram-followers-bot#25]
@ricardojoserf  Just wanted to say thanks for this awesome script, was exactly what i was looking for, tried 2 other scripts, one python and the other shell and neither worked, this has saved me soooo much time, cant imagine doing this manually, many thanks goes to @paulohenriquesn to, i was looking for exactly this option, thanks alot for including it 👌🏽

**Comment by ricardojoserf** [comment]
Thank you @quadroli! It takes me time to maintain the project, but messages like this make my day :)
