### ISSUE TITLE
Bug json

### ISSUE THREAD

**Issue by gab1992** [ricardojoserf/instagram-followers-bot#27]
## Specifications

 - Operative system: Kali Linux

 - Version (e.g. Python version): 3.8.6

## Steps to Reproduce the Problem
python main.py -u USERNAME -p PASSWORD -o super-followback:

After 15 unfollow I get this error 
`Traceback (most recent call last):
  File "main.py", line 158, in <module>
    main()
  File "main.py", line 141, in main
    super_unfollow()
  File "main.py", line 95, in super_unfollow
    user_id = aux_funcs.get_id(i)
  File "/home/gab/Desktop/instagram-followers-bot/aux_funcs.py", line 19, in get_id
    respJSON = response.json()
  File "/home/gab/.local/lib/python3.8/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by ricardojoserf** [comment]
Hi @gab1992 !!!
Please change the value of the variables in lines 10 and 11:
min_delay = 5
max_delay = 10

To a higher value, for example:
min_delay = 10
max_delay = 20

And please let me know if this problem still exists :)

**Comment by gab1992** [comment]
Hi,

I changed to 15 25 even but still the same error after 4 unfollow !

**Comment by ricardojoserf** [comment]
Hi @gab1992 thank you for answering. Could you let me know if the account is flagged? Can you log in correctly?
The other 2 options that could cause this is that there is a problem getting the ID of the username you are trying to unfollow (could you let me know the username causing this?) or that we are causing a problem using the same user agent repeatdly (in that case I should create a branch to test this and I would need your feedback because I do not have an account in which I could test this, would that be alright?)

**Comment by gab1992** [comment]
Hi,

I don't know what you mean by flagged ? But yes I can log in correctly no problem.
I can't tell you the username as it doesn't appear, or where could I get the information ?

I was also thinking of another problem : I follow a lot of private account, and when I unfollow manually, a pop up appear "are you sure you want to unfollow this person ?" with to option basically yes and no, I am thinking maybe it's when the program send try to unfollow a private account that the bug appear ?

No problem for testing, I will keep updating you with the test and errors that might appears.

Thank you :)

**Comment by ricardojoserf** [comment]
Hi @gab1992! Thank you for your help! Please download the dev branch and let us see if the problem has been solved or we must try something else. You can get it in here:
https://github.com/ricardojoserf/instagram-followers-bot/tree/dev
Let me know if this works better or the same ;)

**Comment by gab1992** [comment]
It's working like a charm ! What was the fix ?
Good job man ;)

**Comment by gab1992** [comment]
oh well`Note: There was an error unfollowing nameoftheaccount, please try again later.
`
I think I reached the instagram limit this time, I already unfollow a lot of people. I think it is not the program itself this time.

**Comment by ricardojoserf** [comment]
Great! Can I know if after that message the script stops or keeps unfollowing accounts? I think you may be right and it is the instagram limit. I think I will add some more functionality and then merge this branch with the main one! Close the issue whenever you want :)

**Comment by gab1992** [comment]
I now can confirm it's normal instagram limit. The program keeps running, I think you should add that IF "note : there was an error" THEN "you reach insatgram unfollowing limit, program will end" and then make program end. Or something along that.

Great program !
