### ISSUE TITLE
Login not successful

### ISSUE THREAD

**Issue by 89z** [ricardojoserf/instagram-followers-bot#46]
Using this command:

~~~
python main.py -u srpen6 -p PASSWORD -o info
~~~

I get this result:

~~~
Login not successful
Traceback (most recent call last):
  File "D:\Desktop\instagram-followers-bot-master\main.py", line 187, in <module>
    main()
  File "D:\Desktop\instagram-followers-bot-master\main.py", line 143, in main
    for i in api.getTotalSelfFollowers():
  File "D:\Desktop\instagram-followers-bot-master\LevPasha\InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: 'InstagramAPI' object has no attribute 'username_id'
~~~

**Comment by ricardojoserf** [comment]
Hi @89z , please check your username and password are correct. If your password uses characters such as "$", please create an wnvironment variable (p="YourPass$$w0rd"), then echo it to check it is right (echo $p) and then use it to call the script (python main.py -u srpen6 -p $p -o info)
Please let me know if that fixs it

**Comment by 89z** [comment]
Looks like I was temporarily locked out. I was making several login requests while developing some software. Nothing bad, I was just making login requests to make sure that the login code worked. Now that the lock is removed, I finished my code, and I just export the `Ig-Set-Authorization` value. Thanks!

**Comment by ricardojoserf** [comment]
Good to know 👍🏻
