### ISSUE TITLE
Instagram API changed?

### ISSUE THREAD

**Issue by getmnydev** [ricardojoserf/instagram-followers-bot#5]
When running ```python main.py -u USERNAME -p PASSWORD -o super-unfollow```, I get error:

```Login not successful
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    main()
  File "main.py", line 113, in main
    for i in api.getTotalSelfFollowers():
  File "/home/dinhjeffrey/Desktop/instagram-followers-bot/LevPasha/InstagramAPI.py", line 162, in getTotalSelfFollowers
    return self.getTotalFollowers(self.username_id)
AttributeError: InstagramAPI instance has no attribute 'username_id'```

**Comment by ricardojoserf** [comment]
Hi @getmnydev . I just tested the "super-unfollow" functionality and it is working fine for me. Please wait some minutes (maybe you are using the script too often) and check Instagram is not asking you to add a phone number to the account. Are you working on Linux right? Can you please tell me if you have used it before or just trying this for the first time? 

Thank you

**Comment by ricardojoserf** [comment]
Also, please use "git pull" to get the last version :)

Thanks

**Comment by getmnydev** [comment]
Hey @ricardojoserf , thanks for the reply. I've used it for several weeks now and using it on Linux. I git pulled the latest version as well. I did see Instagram ask me to confirm if I logged into a new location, but after clicking that I'm still getting the same error. Maybe I will wait a day and see if it gets better, thanks!

**Comment by ricardojoserf** [comment]
Great, let's talk tomorrow then! :)

**Comment by getmnydev** [comment]
It worked now, thanks @ricardojoserf for the quick support and awesome bot
