### ISSUE TITLE
Error getting informations

### ISSUE THREAD

**Issue by jack75015** [ricardojoserf/instagram-followers-bot#8]
Hey,

I tried to get informations about my instagram account:
`python main.py -u USERNAME -p PASSWORD -o info
`
And I get this error:
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import aux_funcs, sys, json, time, random
  File "/Users/xxx/Documents/instagram-followers-bot/aux_funcs.py", line 1, in <module>
    import sys, json, requests, os
ImportError: No module named requests`

I think the program have to be uptated with the new API/Standarts of Instragam ?

**Comment by ricardojoserf** [comment]
Hi @jack75015 ! It seems a dependencies problem. Are you using Windows, Linux or MacOS? I think it may be solved by installing the requests module (running "pip install requests")

Regards,

Ricardo

**Comment by jack75015** [comment]
Hello @ricardojoserf 
Im using MacOS terminal for it :)
I think my modules are updated

> pip3 install requests
Requirement already satisfied: requests in /usr/local/lib/python3.7/site-packages (2.22.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests) (2019.6.16)

**Comment by ricardojoserf** [comment]
Hello again @jack75015 . "No module named requests" means the "requests" module is not installed or can not be found. If you could find an executable called pip or pip3 inside the bin folder where you python is installed, try to run "pip install requests" or "pip3 install requests". 
Also, are you running Python2 or Python3?

Regards,

Ricardo

**Comment by jack75015** [comment]
Hello @ricardojoserf 
You were right, the missing module was requests_toolbelt
I did a 
`pip3 install requests_toolbelt`

and now it's work :)

Thanks for the help, and for the python bot coding =)

**Comment by ricardojoserf** [comment]
Glad to hear that @jack75015 ! Feel free to star the repo if you like it ;)

REgards,

Ricardo
